language: node_js
node_js:
   - 14

cache:
    directories:
        - node_modules
# deploy:
#   - provider: s3
#     access_key_id: $AWS_ACCESS_KEY_ID
#     secret_access_key: $AWS_SECRET_ACCESS_KEY
#     local_dir: dpl_cd_upload 
#     skip_cleanup: true
    
#     bucket: "duocun-wx-api"
#     region: us-east-1
#     on: &2
#         repo: duocun/duocun-wx-api
#         branch: develop

#   - provider: codedeploy
#     access_key_id: $AWS_ACCESS_KEY_ID
#     secret_access_key: $AWS_SECRET_ACCESS_KEY
#     bucket: "duocun-wx-api"
#     key: latest.zip
#     bundle_type: zip
#     application: "duocun-wx-api"
#     deployment_group: "dc-wx-api-group"
#     region: us-east-1
#     on: *2

# script:
#     - zip -r latest *
#     - mkdir -p dpl_cd_upload
#     - mv latest.zip dpl_cd_upload/latest.zip
